use sequelles::Insert;

use crate::structs::PieInsert;
use crate::structs::PieTopping;
use crate::structs::ToppingInsert;

pub async fn inserts(conn: &mut sqlx::SqliteConnection) {
    // To create a new row, we have a special struct for it. It's called [RowStruct]Insert.
    // It's the same as [RowStruct], but auto_increment and default values have been made optional.
    // You may want to set those values, or not. Up to you!

    // You can create the struct by destructuring...
    let _apple_pie = PieInsert {
        name: "Apple Pie".to_string(),
        barcode: "123ThisIsNotEANCompliant!".into(),
        description: None,
        id: None,
        price: None,
    };

    // ... But this is boring. Instead, you can use a builder, generated by `bon`
    let apple_pie = PieInsert::builder()
        .name("Apple pie")
        .barcode("123ThisIsNotEANCompliant!")
        .price(5.25)
        .build();

    // Then... Insert. That's it!
    let apple_pie = apple_pie.insert(conn).await.unwrap().unwrap();

    // Let's add more data for our exemples

    let apples = ToppingInsert::builder()
        .name("Apple")
        .build()
        .insert(conn)
        .await
        .unwrap()
        .unwrap();

    // You can also insert a table row directly
    PieTopping {
        pie_id: apple_pie.id,
        topping_id: apples.id,
    }
    .insert(conn)
    .await
    .unwrap();

    // Beware that you want to keep the result of the insert, not the row. 
    // This is simply because the database may edit the inserted row in triggers, or set defaults
    // Also, if insertion fails, it will return a None in some sql dialects
}
